<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Lenovo EBGLMS for Moodle 3.7+. Functions used by related courses.
 *
 * @package    local
 * @subpackage swtc
 * @copyright  2019 Lenovo DCG Education Services
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * History:
 *
 *	06/10/19 - Initial writing.
 * 07/18/19 - In local_swtc_rc, changed field "courseids" to "courseid"; added row for each
 *                      courseid (not grouping courseids anymore); added "active" field; added logic for checking
 *                      "new" related courses against the one's currently in the database.
 * 07/21/19 - Added functions used by modified couse_slider block.
 * 07/26/19 - Removed relatedcourses_block_course_slider_exists and relatedcourses_block_course_slider_dynamically_add
 *                      (since we will be using Moosh to add the course_slider block to all courses).
 * 08/09/19 - Added function to track clicks from swtc_rc_course_slider block.
 * 08/19/19 - Added relatedcourses_getall and relatedcourses_capture_click.
 * 08/20/19 - Added relatedcourses_capture_enrollment to see if this enrollment was generated by a previous click
 *                  on a related course.
 * 08/22/19 - Changed table names to "local_swtc_sc"and "local_swtc_rc"; moved relatedcourses_getall to
 *                  /local/swtc/lib/locallib.php as local_swtc_get_all_courses.
 * 08/23/19 - Moved relatedcourses_capture_click to /local/swtc/lib/locallib.php as local_swtc_capture_click.
 * 08/26/19 - Moved relatedcourses_capture_enrollment to /local/swtc/lib/locallib.php as local_swtc_capture_enrollment.
 *	10/16/19 - Changed to new Lenovo EBGLMS classes and methods to load swtc_user and debug.
 * 12/10/19 - In relatedcourses_get_courses, changed the way related courses are found (in curriculum or same category if a PA course). In
 *                          other words the course "course_format_options" is NOT checked anymore.
 *
 */

defined('MOODLE_INTERNAL') || die();

// Lenovo ********************************************************************************.
// Include Lenovo EBGLMS user and debug functions.
// Lenovo ********************************************************************************.
require_once($CFG->dirroot.'/local/swtc/lib/swtc_userlib.php');
require_once($CFG->dirroot.'/local/swtc/lib/locallib.php');                     // Some needed functions.
require_once($CFG->dirroot.'/local/swtc/lib/swtc_constants.php');   // Include constants.
require_once($CFG->dirroot.'/local/swtc/lib/curriculumslib.php');         // Curriculum functions.

/**
 * Saves (puts) all the related courses for a particular course (stored in table local_swtc_rc).
 *
 * @param $integer   Parent courseid.
 * @param $array   Array of courses.
 *
 * @return $bool   Success.
 *
 * History:
 *
 * 08/16/19 - Initial writing.
 * 08/22/19 - Changed table names to "local_swtc_sc" and "local_swtc_rc".
 *
 **/
function relatedcourses_put_courses($parentcourseid, $relatedcourses) {
    global $CFG, $DB, $SESSION, $USER;

    // Lenovo ********************************************************************************.
    // Lenovo EBGLMS swtc_user and debug variables.
    $swtc_user = swtc_get_user($USER);
    $debug = swtc_get_debug();

    // Other Lenovo variables.
    $params = array();
    // Lenovo ********************************************************************************.

    if (isset($debug)) {
        $messages[] = "In /local/swtc/lib/relatedcourseslib.php ===relatedcourses_put_courses.enter===";
        debug_logmessage($messages, 'both');
        unset($messages);
    }

    // Clean input.
    $relatedcourses = clean_param_array($relatedcourses, PARAM_NOTAGS);

    // Lenovo ********************************************************************************.
    // For the parent course, get all the currently active related courses.
    // Lenovo ********************************************************************************.
    $params = array($DB->sql_compare_text('parentcourseid') => $parentcourseid, 'active' => COURSE_ACTIVE);
    $currently_active = $DB->get_records('local_swtc_rc', $params);
    // print_object($relatedcourses);
    // print_object($currently_active);

    // Lenovo ********************************************************************************.
    // Loop through each of the currently active related courses and:
    //      If currently active (CA) course is NOT in new active (NA) courses:
    //          - Set CA course "active" to 0 (inactive).
    //          - Update CA course modified date / time.
    //          - Update CA course modified userid.
    //      If CA course is IN NA courses:
    //          - Update CA course modified date / time.
    //          - Update CA course modified userid.
    // Lenovo ********************************************************************************.
    foreach($currently_active as $current) {
        // print_object($current);
        if (in_array($current->relatedcourseid, $relatedcourses)) {
            // Course exists. Will update timemodified and usermodified later.
            // print_r("course exists.\n");
        } else {
            // Course does NOT exist. Update "active" and other fields.
            // print_r("course does NOT exist. setting $current->courseid to inactive.\n");
            // Update the timemodified, get the USER->id of the user, and set "active" to inactive.
            $params['id'] = $current->id;
            $params['active'] = COURSE_INACTIVE;
            $params['timemodified'] = time();
            $params['usermodified'] = $USER->id;

            // Update the record.
            $DB->update_record('local_swtc_rc', $params);
        }
    }

    foreach($relatedcourses as $courseid) {
        // Lenovo ********************************************************************************.
        // Update the record if it exists.
        // Lenovo ********************************************************************************.
        $params = array($DB->sql_compare_text('parentcourseid') => $parentcourseid, 'relatedcourseid' => $courseid, 'active' => COURSE_ACTIVE);
        if ($DB->record_exists('local_swtc_rc', $params)) {
            $record = $DB->get_record('local_swtc_rc', $params);

            // Only update the timemodified, and therefore the courses, if we have changed the course to be saved.
            // Update the timemodified, get the USER->id of the user, and set "active" to active.
            $params['id'] = $record->id;
            $params['active'] = COURSE_ACTIVE;
            $params['timemodified'] = time();
            $params['usermodified'] = $USER->id;

            // Add the record.
            $DB->update_record('local_swtc_rc', $params);
        } else {
            // Lenovo ********************************************************************************.
            // Create the record if it doesn't exist yet.
            // Lenovo ********************************************************************************.
            // Update the timecreated, get the USER->id of the user, and set "active" to active.
            $params['active'] = COURSE_ACTIVE;
            $params['usercreated'] = $USER->id;
            $params['timecreated'] = time();
            $params['usermodified'] = 0;
            $params['timemodified'] = 0;
            $params['parentcourseid'] = $parentcourseid;
            $params['relatedcourseid'] = $courseid;
            $params['clicks'] = 0;
            $params['enrollments'] = 0;
            // print_object("about to print params");
            // print_object($params);

            $recordid = $DB->insert_record('local_swtc_rc', $params, true);
        }
    }

    if (isset($debug)) {
        $messages[] = "In /local/swtc/lib/relatedcourseslib.php ===relatedcourses_put_courses.exit===";
        debug_logmessage($messages, 'both');
        unset($messages);
    }

    return true;

}

/**
 * Gets all the related courses for a particular course. The logic flow for determining related courses is:
 *      if (the course belongs to any curriculum(s) and the course is NOT a PA) then
 *          list all the other courses in the curriculum as related courses
 *      else if (the course is a PA) then
 *          list all the other PA courses in the category as related courses
 *      else ***The course is not in any curriculum and is NOT a PA
 *          list the Service Provider Curriculum Base courses as related courses
 *
 * @param $integer  The parent courseid.
 *
 * @return $array   Array of related courses or empty array if none.
 *
 * History:
 *
 * 08/01/19 - Initial writing.
 * 12/10/19 - In relatedcourses_get_courses, changed the way related courses are found (in curriculum or same category if a PA course). In
 *                          other words the course "course_format_options" is NOT checked anymore.
 *
 **/
function relatedcourses_get_courses($courseid) {
    global $CFG, $DB, $COURSE, $SESSION, $USER;

    // Lenovo ********************************************************************************.
    // Lenovo EBGLMS swtc_user and debug variables.
    $swtc_user = swtc_get_user($USER);
    $debug = swtc_get_debug();

    // Other Lenovo variables.
    $relatedcourses = array();
    $params = array();
    $pastring = 'PA';
    // Lenovo ********************************************************************************.

    // Get all the entire course record.
    $params = array('id' => $courseid);
    $record = $DB->get_record('course', $params, '*', MUST_EXIST);

    if (isset($debug)) {
        $messages[] = "In /local/swtc/lib/relatedcourseslib.php ===relatedcourses_get_courses.enter===";
        // $messages[] = "About to print record.";
        // $messages[] = print_r($record, true);
        // $messages[] = "Finished printing record.";
        // print_object($record);
        debug_logmessage($messages, 'both');
        unset($messages);
    }

    // Lenovo ********************************************************************************.
    // Determine if the course is a PA.
    // Lenovo ********************************************************************************.
    if (substr_compare ($record->shortname, $pastring, 0, strlen($pastring)) == 0) {
        $patype = true;
    } else {
        $patype = null;
    }

    // Lenovo ********************************************************************************.
    // If the course is NOT a PA, see if the course is part of any curriculum. If so, load all the courses.
    // Lenovo ********************************************************************************.
    if (!isset($patype)) {
        $course_partof_curriculum = curriculum_courses_find_course($courseid);

        // If this course it is part of ANY curriculum, get a list of all those courses.
        if (isset($course_partof_curriculum)) {
            $curriculums = explode(', ', $course_partof_curriculum->curriculums);

            foreach($curriculums as $curriculum) {
                // print_object($curriculum);
                // Get all the courses in the curriculum.
                $courses = curriculum_courses_list($curriculum);
                // print_object($courses);
            }
        }

    // Lenovo ********************************************************************************.
    // If the course is a PA, list all the courses in the same category as related courses.
    // Lenovo ********************************************************************************.
    } else if ($patype) {

        // Save the category (path) to the course.
        $category = $record->category;

        // See if they're any other courses in the category (we know there is at least one...).
        $courses = $DB->get_records('course', array('category' => $category), 'sortorder ASC');
    }

    // Lenovo ********************************************************************************.
    // If we found some courses above, add them to relatedcourses.
    // Lenovo ********************************************************************************.
    // print_object($courses);
    if (!empty($courses)) {
        foreach($courses as $course) {
            if ($course->id !== $COURSE->id) {
                $relatedcourses[$course->id] = $course->id;
            }
        }
    }

    // Lenovo ********************************************************************************.
    // If relatedcourses is still empty at this point, load all the courses in the Service Provider Base curricum (as a default
    //              list of courses).
    // Lenovo ********************************************************************************.
    if (empty($relatedcourses)) {
        // Get all the entire course record.
        $params = array('shortname' => 'SPC0010');
        $rec = $DB->get_record('course', $params, '*', MUST_EXIST);

        $courses = curriculum_courses_list($rec->id);

        foreach($courses as $course) {
            if ($course->id !== $COURSE->id) {
                $relatedcourses[$course->id] = $course->id;
            }
        }
    }

    if (isset($debug)) {
        $messages[] = "About to print relatedcourses.===";
        $messages[] = print_r($relatedcourses, true);
         // print_object($relatedcourses);
        $messages[] = "Finished printing relatedcourses.===";
        $messages[] = "In /local/swtc/lib/relatedcourseslib.php ===relatedcourses_get_courses.exit===";
        debug_logmessage($messages, 'both');
        unset($messages);
    }

    return $relatedcourses;

}
